# CMake generated Testfile for 
# Source directory: /home/smsrkursat/ns-allinone-3.41/ns-3.41/src/network/examples
# Build directory: /home/smsrkursat/ns-allinone-3.41/ns-3.41/cmake-cache/src/network/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-bit-serializer "ns3.41-bit-serializer-default")
set_tests_properties(ctest-bit-serializer PROPERTIES  WORKING_DIRECTORY "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-main-packet-header "ns3.41-main-packet-header-default")
set_tests_properties(ctest-main-packet-header PROPERTIES  WORKING_DIRECTORY "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-main-packet-tag "ns3.41-main-packet-tag-default")
set_tests_properties(ctest-main-packet-tag PROPERTIES  WORKING_DIRECTORY "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-packet-socket-apps "ns3.41-packet-socket-apps-default")
set_tests_properties(ctest-packet-socket-apps PROPERTIES  WORKING_DIRECTORY "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/network/examples/CMakeLists.txt;0;")
add_test(ctest-lollipop-comparisons "ns3.41-lollipop-comparisons-default")
set_tests_properties(ctest-lollipop-comparisons PROPERTIES  WORKING_DIRECTORY "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build/src/network/examples/" _BACKTRACE_TRIPLES "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/network/examples/CMakeLists.txt;13;build_lib_example;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/network/examples/CMakeLists.txt;0;")
