# CMake generated Testfile for 
# Source directory: /home/smsrkursat/ns-allinone-3.41/ns-3.41/src/lorawan/examples
# Build directory: /home/smsrkursat/ns-allinone-3.41/ns-3.41/cmake-cache/src/lorawan/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-simple-network-example "ns3.41-simple-network-example-default")
set_tests_properties(ctest-simple-network-example PROPERTIES  WORKING_DIRECTORY "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/lorawan/examples/CMakeLists.txt;1;build_lib_example;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-network-server-example "ns3.41-network-server-example-default")
set_tests_properties(ctest-network-server-example PROPERTIES  WORKING_DIRECTORY "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/lorawan/examples/CMakeLists.txt;8;build_lib_example;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-complete-network-example "ns3.41-complete-network-example-default")
set_tests_properties(ctest-complete-network-example PROPERTIES  WORKING_DIRECTORY "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/lorawan/examples/CMakeLists.txt;16;build_lib_example;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-adr-example "ns3.41-adr-example-default")
set_tests_properties(ctest-adr-example PROPERTIES  WORKING_DIRECTORY "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/lorawan/examples/CMakeLists.txt;24;build_lib_example;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-lorawan-energy-model-example "ns3.41-lorawan-energy-model-example-default")
set_tests_properties(ctest-lorawan-energy-model-example PROPERTIES  WORKING_DIRECTORY "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/lorawan/examples/CMakeLists.txt;32;build_lib_example;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-aloha-throughput "ns3.41-aloha-throughput-default")
set_tests_properties(ctest-aloha-throughput PROPERTIES  WORKING_DIRECTORY "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/lorawan/examples/CMakeLists.txt;40;build_lib_example;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-parallel-reception-example "ns3.41-parallel-reception-example-default")
set_tests_properties(ctest-parallel-reception-example PROPERTIES  WORKING_DIRECTORY "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/lorawan/examples/CMakeLists.txt;48;build_lib_example;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/lorawan/examples/CMakeLists.txt;0;")
add_test(ctest-frame-counter-update "ns3.41-frame-counter-update-default")
set_tests_properties(ctest-frame-counter-update PROPERTIES  WORKING_DIRECTORY "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build/src/lorawan/examples/" _BACKTRACE_TRIPLES "/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;47;add_test;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-executables.cmake;122;set_runtime_outputdirectory;/home/smsrkursat/ns-allinone-3.41/ns-3.41/build-support/custom-modules/ns3-module-macros.cmake;542;build_exec;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/lorawan/examples/CMakeLists.txt;56;build_lib_example;/home/smsrkursat/ns-allinone-3.41/ns-3.41/src/lorawan/examples/CMakeLists.txt;0;")
